# Generated by Django 5.0.6 on 2024-09-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_alter_tree_audio_link_alter_tree_common_name_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bookmarks',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to='trees.tree'),
        ),
    ]
