# Generated by Django 5.0.6 on 2024-09-16 17:55

import trees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=255, unique=True)),
                ('botanical_name', models.CharField(blank=True, max_length=255, null=True)),
                ('habitant', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('information', models.TextField(blank=True, null=True)),
                ('medical_use', models.TextField(blank=True, null=True)),
                ('image_link', models.ImageField(blank=True, null=True, upload_to=trees.models.tree_image_file_path)),
                ('audio_link', models.FileField(blank=True, null=True, upload_to=trees.models.tree_audio_file_path)),
            ],
        ),
    ]
