# Generated by Django 5.0.6 on 2024-09-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='audio_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='common_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
