# Generated by Django 5.0.6 on 2024-09-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_alter_tree_audio_link_alter_tree_common_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='audio_link',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='image_link',
        ),
        migrations.AddField(
            model_name='tree',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='tree',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
