# Generated by Django 5.0.6 on 2024-09-12 22:24

import trees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_remove_tree_audio_link_remove_tree_image_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='image',
        ),
        migrations.AddField(
            model_name='tree',
            name='audio_link',
            field=models.FileField(blank=True, null=True, upload_to=trees.models.tree_video_file_path),
        ),
        migrations.AddField(
            model_name='tree',
            name='image_link',
            field=models.ImageField(blank=True, null=True, upload_to=trees.models.tree_image_file_path),
        ),
    ]
